# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20161021_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='item_id',
        ),
        migrations.AddField(
            model_name='wish',
            name='item',
            field=models.CharField(default='stuff', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
