# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_auto_20161021_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='item',
        ),
        migrations.AddField(
            model_name='wish',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wish_list.Item'),
            preserve_default=False,
        ),
    ]
